Share the etcd watcher
v6d-io/v6d pull request #1007
Opened 2022-09-28 11:13 UTC by shihao-thx

Signed-off-by: shihao-thx <shihao@zju.edu.cn>

What do these changes do?
-------------------------

as titled.

Related issue number
--------------------

Fixes #715.

2022-10-09 12:35 UTC, shihao-thx commented
Hi, @sighingnow. Sharing the etcd watcher has already done. If there are any problems, please let me know. Thanks!

2022-10-13 06:36 UTC, sighingnow commented
> Hi, @sighingnow. Sharing the etcd watcher has already done. If there are any problems, please let me know. Thanks!

Will take a review later today.

2022-10-13 06:48 UTC, sighingnow requested changes
Please implement the `EtcdWatchHandler::operator()` as review comments.

2022-10-13 06:48 UTC, sighingnow commented on src/server/services/etcd_meta_service.cc
> +      std::make_shared<SessionInfo>(sessionID, pems, ctx, callback, prefix));
Use a `std::map<SessionID, SessionInfo>` to simplify logic in handlers.

2022-10-13 06:48 UTC, sighingnow commented on src/server/services/etcd_meta_service.cc
> +      }
I suggest you first split and group events to sessions, then dispatch events to each session, e.g.,

```
std::map<std::string /*prefix*/, std::vector<etcd::Event>>  event_groups;

for (auto const &event: resp.events()) {
    std::string const& key = event.kv().key();
    if (key.starts_with("/s")) { // it should belong to some session, and you know the length of session prefix
        event_groups[key.substr(1, 8 /* maybe */)].emplace_back(event);
    }
}

// then dispatch events to sessions

for (auto const &group: event_groups) {
    auto const &session = sessions_[group.first];
    for (auto const &event: group.second) {
         // processing the events, as existing logic
    }
}

```

2022-10-13 06:48 UTC, sighingnow commented on src/server/services/etcd_meta_service.h
> +      std::unique_ptr<etcd::Client>& etcd_);
Looks strange that `WatcherHanlder` has method to initialize a `Watcher` ....

2022-10-13 06:50 UTC, sighingnow commented
If it is possible, I suggest you consider unify the watcher handler logic in both etcd metadata service and the redis metadata service, as they share a lot of common stuffs.

2022-10-13 12:01 UTC, shihao-thx commented
Thanks for the suggestions. I'll do that as soon as possible.

2022-10-17 14:50 UTC, shihao-thx commented
I modified the way to dispatch watch events to sessions as suggested. If it's fine, I'll try to apply it to sharing redis metadata watcher in a few days.

2022-10-18 02:20 UTC, sighingnow commented
> I modified the way to dispatch watch events to sessions as suggested. If it's fine, I'll try to apply it to sharing redis metadata watcher in a few days.

Please go ahead.

2022-10-18 02:29 UTC, shihao-thx commented
I noticed the `spill_test` failed, but it can pass on my PC. Should I deal with it?

2022-10-18 03:04 UTC, sighingnow commented
The crash happened inside vineyardd:

![image](https://user-images.githubusercontent.com/7144772/196325994-95c65024-ba5a-4222-9be2-af070b62fad5.png)

Looks caused by this pull request.

2022-10-23 09:04 UTC, shihao-thx commented
Hi, @sighingnow . Sharing the redis watcher has already done too. If there are any problems, please let me know. Thanks!

2022-10-24 01:34 UTC, sighingnow approved these changes
LGTM now.

Will merge after repeat the CI for several times to confirm the correctness.

2022-10-24 02:08 UTC, sighingnow commented
Merged. Thanks!

2022-10-24 02:09 UTC, merged