Hive
v6d-io/v6d pull request #1441
Opened 2023-06-29 11:19 UTC by vegetableysm

What do these changes do?
-------------------------

Support vineyard as a storage backend of hive.

Related issue number
--------------------

Fixes #1420

2023-06-30 07:19 UTC, sighingnow commented on java/core/src/main/java/io/v6d/core/client/IPCClient.java
> +    }
`BufferBuilder` itself already has a `seal()`, method.

2023-07-18 06:01 UTC, sighingnow requested changes

2023-07-20 03:34 UTC, vegetableysm commented on java/hive/src/main/java/io/v6d/hive/ql/io/VineyardRowInputFormat.java
> +    private void prepare() throws VineyardException{
Done

2023-07-20 03:34 UTC, vegetableysm commented on java/hive/src/main/java/io/v6d/hive/ql/io/VineyardRowInputFormat.java
> +    private VectorSchemaRoot getSchemaRoot() {
Done

2023-07-20 03:35 UTC, vegetableysm commented on java/modules/basic/src/main/java/io/v6d/modules/basic/tensor/TensorBuilder.java
> +package io.v6d.modules.basic.tensor;
Get!

2023-07-25 01:36 UTC, sighingnow requested changes

2023-07-27 01:57 UTC, vegetableysm commented on java/hive/README.rst
> +    and the data will be written to the same partition, which will cause the data to be written incorrectly.
fixed

2023-08-22 02:09 UTC, sighingnow commented
Closing as in favour of #1520

2023-08-22 02:09 UTC, closed without merging