add unit test for vineyardctl
v6d-io/v6d pull request #1499
Opened 2023-08-01 02:16 UTC by zhuyi1159

What do these changes do?
-------------------------

add unit test for vineyardctl

Related issue number
--------------------

Fixes #1301

2023-08-02 08:59 UTC, dashanji requested changes
Great job on the PR! I can see that you have made some improvements since the previous version. However, there are still a few points that need attention.

- I notice you rewritten the main part of a command to adapt the input and output of a specific function, it's okay to delete such test cases. Also, it's better to make the unit test more flexible.
- Could you please revise the code to make the unit test more meaningful?
- Please keep an eye out for redundant tests and review the comments accordingly.
- It's essential to double-check unused code and debug information before submitting your PR.
- Be sure to use English for annotations.

Please keep up the good work!

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/sidecar/inject_test.go
> +	testReplicas := struct {
Update the test name here.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/sidecar/inject_test.go
> +		// 获取 PVC 对象
There is no need to test pvc here.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/sidecar/inject_test.go
> +				if container.Image != testReplicas.expectedImage {
It's a bug here. Please fix it as the container of the injected workload is not `vineyardcloudnative/vineyardd:alpine-latest`. Also, could you please check the other parts at the same time?

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/sidecar/inject_test.go
> +			expectedResult: "apiVersion: k8s.v6d.io/v1alpha1\n" +
Please use the single quotation.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/sidecar/inject_test.go
> +				Workload:    `{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"creationTimestamp":null,"name":"nginx-deployment","namespace":"vineyard-system","ownerReferences":[]},"spec":{"selector":{"m
It's hard to maintain the long string, a possible way is to output the string as YAML.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/sidecar/inject_test.go
> +func Test_parseManifestsAsYAML(t *testing.T) {
The test looks very strange, it's okay to delete this.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/sidecar/inject_test.go
> +					Workload:    `{"apiVersion":"apps/v1","kind":"Deployment","metadata":{"creationTimestamp":null,"name":"nginx-deployment","namespace":"vineyard-system","ownerReferences":[]},"spec":{"selector":{"
Looks the same as before, please reuse the previous string here.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/util/format_test.go
No need to test here.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/util/usage/doc_test.go
No need here.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/util/usage/json_test.go
> +	cmd := &cobra.Command{
It is not advisable to create a new command for testing.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/util/usage/md_docs_test.go
No need here.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/util/usage/types_test.go
No need here.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/util/template_test.go
> +	if len(objs) != 0 {
Please specify the number here.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/util/template_test.go
> +	assert.NoError(t, err)
Same as before.

2023-08-02 08:59 UTC, dashanji commented on k8s/cmd/commands/util/template_test.go
> +	assert.NoError(t, err)
Could you please make the test more meaningful?

2023-08-09 15:18 UTC, dashanji requested changes
I roughly reviewed the previous files. There are several issues you need to address.
- Delete the duplicated test functions.
- Every test function is a complete execution unit, please check in your test function and make sure they can be run successfully independently.
- Update the hard-coded path.

Otherwise, please add a GitHub CI to test the unit test.

2023-08-09 15:18 UTC, dashanji commented on k8s/cmd/commands/deploy/deploy_vineyardd_test.go
> +	flags.VineyarddFile = os.Getenv("HOME") + "/v6d/k8s/test/e2e/vineyardd.yaml"
Please DON'T to hard-code the path.

2023-08-15 08:37 UTC, dashanji requested changes
Overall LGTM! There are several hints for you.
- Format several JSON strings to make them easier to read.
- Reduce the duplications and reuse the common parts between unit test functions. 
- Simplify these makefile parts.

2023-08-28 02:07 UTC, sighingnow commented on k8s/test/e2e/Makefile
> +.PHONY: unittest
```suggestion
############# unit testing ################################################
unittest: prepare-e2e-test build-local-cluster load-vineyardd-image
	@make -C ${K8S_DIR} install-cert-manager
	@make -C ${E2E_DIR} install-vineyard-operator
	@echo "Running vineyardctl unit test.." 
    # create test
	@export KUBECONFIG="/tmp/e2e-k8s.config" && cd ${K8S_DIR} && go test ./cmd/commands/create/
   # delete test 
	@export KUBECONFIG="/tmp/e2e-k8s.config" && cd ${K8S_DIR} && go test ./cmd/commands/delete/
  # deploy test
	@export KUBECONFIG="/tmp/e2e-k8s.config" && cd ${CMD_DIR}/commands/deploy && \
		go test -run first && go test -run second && go test -run third 
    # schedule test
	@export KUBECONFIG="/tmp/e2e-k8s.config" && cd ${K8S_DIR} && go test ./cmd/commands/schedule/
    # sidecar test 
	@export KUBECONFIG="/tmp/e2e-k8s.config" && cd ${CMD_DIR}/commands/sidecar && \
		go test -run TestInjectCmd && go test -run Test_deployDuringInjection && go test -run slow
    # util test
	@export KUBECONFIG="/tmp/e2e-k8s.config" && cd ${K8S_DIR} && go test ./cmd/commands/util/
	@echo "vineyardctl unit test passed."
	@make delete-local-cluster
.PHONY: unittest
```

2023-08-29 07:35 UTC, merged

2023-08-29 07:36 UTC, sighingnow commented
Merged. @zhuyi1159  Thanks a lot for your effort!