clean the unused code and prune vineyardctl dependency
v6d-io/v6d pull request #1562
Opened 2023-09-11 02:28 UTC by zhuyi1159

What do these changes do?
-------------------------

as titled

Related issue number
--------------------

Fixes #1268

2023-09-11 02:36 UTC, sighingnow reviewed
Hi @zhuyi1159 Using `testify` in `_test.go` modules should be fine.

2023-09-11 02:56 UTC, zhuyi1159 commented
But `testify` is not widely used. Replacing `testify`with the Golang built-in package `reflect` can reduce two dependencies (there is also an indirect dependency for `testify` )

2023-09-12 07:19 UTC, dashanji commented
@zhuyi1159  Agree to reserve the testify, could you please update the following code from the ginkgo framework to the testify framework? Only reserving one test framework is fine. Also, please update the relevant file name as the test file will be rewritten while adding a new CRD.

https://github.com/v6d-io/v6d/blob/dc61d92fe2920114c0e5139f8424bac91b0ba0de/k8s/controllers/k8s/suite_test.go#L19-L20 

https://github.com/v6d-io/v6d/blob/dc61d92fe2920114c0e5139f8424bac91b0ba0de/k8s/apis/k8s/v1alpha1/webhook_suite_test.go#L24-L25

2023-09-13 02:09 UTC, dashanji commented
@zhuyi1159 Have you tested the `webhook_test.go` and `controller_test.go` locally?

2023-09-13 02:12 UTC, zhuyi1159 commented
Not tested locally.

2023-09-13 02:24 UTC, dashanji requested changes

2023-09-13 02:24 UTC, dashanji commented on k8s/apis/k8s/v1alpha1/webhook_test.go
> +func Test_BeforeSuite(t *testing.T) {
I think you'd better to under how the [ginkgo framework ](https://onsi.github.io/ginkgo/)works. BeforeSuite is used to build the environment for the test suit, you can't update it as a single test function. Also, please check the other similar parts.

2023-09-13 02:24 UTC, dashanji commented on k8s/apis/k8s/v1alpha1/webhook_test.go
> +func Test_AfterSuite(t *testing.T) {
Same as before.

2023-09-13 02:28 UTC, dashanji commented
> Not tested locally.

Could you please add the relevant unit test on CI or test locally? Thank you.

2023-09-14 03:35 UTC, dashanji commented
@zhuyi1159  Please update

https://github.com/v6d-io/v6d/blob/dc61d92fe2920114c0e5139f8424bac91b0ba0de/k8s/apis/k8s/v1alpha1/webhook_suite_test.go#L67

to

```golang
Paths: []string{filepath.Join("..", "..", "..", "config", "webhook","manifests.yaml")}, 
```

2023-09-14 03:45 UTC, dashanji commented
Also, please make sure the version of `kube-apiserver` > v1.19.2

2023-09-14 08:57 UTC, zhuyi1159 commented
Local tests passed.

2023-09-15 05:58 UTC, dashanji approved these changes
Basically LGTM, just one nit.

2023-09-15 05:58 UTC, dashanji commented on k8s/apis/k8s/v1alpha1/webhook_test.go
> +	time.Sleep(1 * time.Second)
Move the sleep after the cancel() to avoid some errors such as the webhook server routine is not exited.

2023-09-15 06:46 UTC, dashanji approved these changes

2023-09-18 03:06 UTC, sighingnow approved these changes

2023-09-18 03:07 UTC, merged