Support to track the chunks by local objects for kubernetes workflow.
v6d-io/v6d pull request #1606
Opened 2023-10-25 08:30 UTC by dashanji

What do these changes do?
-------------------------

As titled. With it, we can schedule the workloads that only produce the localobjects.

2023-10-25 10:28 UTC, sighingnow approved these changes

2023-10-25 10:28 UTC, sighingnow requested changes
Please don't touch the graphar submodule.

2023-10-25 11:10 UTC, dashanji commented
> Please don't touch the graphar submodule.

Sorry, updated.

2023-10-31 07:16 UTC, sighingnow approved these changes

2023-10-31 07:16 UTC, merged