[WIP] Delete the cert manager and generate the self-signed CA for webhook.
v6d-io/v6d pull request #1707
Opened 2024-01-03 13:44 UTC by dashanji

What do these changes do?
-------------------------

As titled.

Related issue number
--------------------

Fixes #1680

2024-01-09 03:49 UTC, sighingnow requested changes

2024-01-09 03:49 UTC, sighingnow commented on k8s/config/crd/kustomization.yaml
>  # +kubebuilder:scaffold:crdkustomizecainjectionpatch
Remove those blocks if they are no longer needed...

2024-01-09 03:49 UTC, sighingnow commented on k8s/config/default/kustomization.yaml
> +#    name: webhook-service
Ditto.

2024-01-09 06:15 UTC, dashanji commented on k8s/config/crd/kustomization.yaml
>  # +kubebuilder:scaffold:crdkustomizecainjectionpatch
Done.

2024-01-09 06:19 UTC, dashanji commented on k8s/config/default/kustomization.yaml
> +#    name: webhook-service
Done.

2024-01-10 04:38 UTC, sighingnow approved these changes

2024-01-10 04:38 UTC, merged