[FEATURE-316] Condition to check maximum shared memory size
v6d-io/v6d pull request #322
Opened 2021-06-20 14:00 UTC by Rohan-cod

Signed-off-by: rohangupta <rohaninjmu@gmail.com>

## What do these changes do?
Added a condition to check the **maximum shared memory size** and raise a **warning** when it is **less** than the value of the `size` parameter.

## Related issue number

Fixes #316

2021-06-21 02:13 UTC, sighingnow commented
Hi @Rohan-cod,

Thanks for the effort, and current implementation won't work on Mac. For more information about obtaining the value of `shmmax`, please refer to https://developer.apple.com/library/archive/documentation/System/Conceptual/ManPages_iPhoneOS/man3/sysctl.3.html and a reference implementation here https://github.com/nicobou/shmdata/blob/develop/shmdata/sysv-shm.cpp#L88

2021-06-21 10:25 UTC, Rohan-cod commented
Hi @sighingnow, 
Actually, I have a mac and I tried running the following code:
```
// temp.cc
#include <sys/statvfs.h>
#include <iostream>
using namespace std;

int main() {
    struct statvfs diskData;
    statvfs("/", &diskData);
    float f_bavail = diskData.f_bavail;
    float f_frsize = diskData.f_frsize;
    float available = f_bavail * f_frsize / (1024 * 1024);
    cout << available << "\n";
}
```

It ran without any errors. Here is the output:
![Screenshot 2021-06-21 at 3 52 51 PM](https://user-images.githubusercontent.com/47586886/122747532-ca947e00-d2a8-11eb-9d9e-dc6024f79893.jpg)

2021-06-22 02:32 UTC, sighingnow commented
> Actually, I have a mac and I tried running the following code:

What we need is the available "shared memory" size, not the size of `/` parition.

2021-06-22 08:25 UTC, Rohan-cod commented
@sighingnow, is this correct:

```
// temp.cc
#include <sys/statvfs.h>
#include <iostream>
using namespace std;

int main() {
#ifdef __linux__
	char path[] = "/dev/shm";
#else
	char path[] = "/tmp";
#endif
	struct statvfs diskData;
	statvfs(path, &diskData);
	float f_bavail = diskData.f_bavail;
	float f_frsize = diskData.f_frsize;
	float available = f_bavail * f_frsize / (1024 * 1024);
	cout << "Available -> " << available << "\n";
}
```

Output:
![Screenshot 2021-06-22 at 1 54 38 PM](https://user-images.githubusercontent.com/47586886/122890568-6bdf0b00-d361-11eb-9085-b456a0c5297d.jpg)

2021-06-22 08:31 UTC, sighingnow commented
Hi @Rohan-cod, the available size of `/tmp` directory is not the same as **shared memory size limit**, which is governed by the system configuration `kern.sysv.shmmax`.

You could refer the implementation in https://github.com/nicobou/shmdata/blob/develop/shmdata/sysv-shm.cpp#L88.

2021-06-22 10:25 UTC, Rohan-cod commented
Hi @sighingnow, I updated the code according to [this](https://github.com/nicobou/shmdata/blob/develop/shmdata/sysv-shm.cpp#L88):

```
// temp.cc
#include <iostream>
#include <stdio.h>
#ifdef __linux__
#ifndef SHMMAX_SYS_FILE
#define SHMMAX_SYS_FILE "/proc/sys/kernel/shmmax"
#endif
#ifndef SHMMNI_SYS_FILE
#define SHMMNI_SYS_FILE "/proc/sys/kernel/shmmni"
#endif
#else
#include <sys/sysctl.h>
#include <sys/types.h>
#endif 

using namespace std;

int main() {
#ifdef __linux__
  unsigned long shmmax = 0;
  FILE* shmmax_file = fopen(SHMMAX_SYS_FILE, "r");
  if (!shmmax_file) {
  	cout << "error" << "\n";
  }
  if (fscanf(shmmax_file, "%lu", &shmmax) != 1) {
    fclose(shmmax_file);
    cout << "error" << "\n";
  }
  fclose(shmmax_file);
  cout << "shmmax -> " << shmmax << "\n";
#else
  unsigned long shmmax = 0;
  size_t len = sizeof(shmmax);
  if (-1 == sysctlbyname("kern.sysv.shmmax", &shmmax, &len, NULL, 0)) {
    cout << "error" << "\n";
  }
  cout << "shmmax -> " << shmmax << "\n";
  
#endif
}
```

Output (on MAC):
![Screenshot 2021-06-22 at 3 52 09 PM](https://user-images.githubusercontent.com/47586886/122908513-d39d5200-d371-11eb-856e-7479e375ee12.jpg)

If it is correct I'll update the PR. :)

2021-06-22 10:53 UTC, sighingnow commented
Yes, I think it works. Go ahead!

2021-06-22 11:27 UTC, Rohan-cod commented
Hi @sighingnow, I just updated the code according to [this](https://github.com/nicobou/shmdata/blob/develop/shmdata/sysv-shm.cpp#L88). :)

2021-06-22 11:30 UTC, sighingnow requested changes
You need to make sure your code passes the compilation first, and test it by specifying a large value to the `--size` parameter to check if it raises a warning as expected.

2021-06-22 11:30 UTC, sighingnow commented on src/server/memory/allocator.cc
Leave a blank line between the different include header groups.

2021-06-22 11:30 UTC, sighingnow commented on src/server/memory/allocator.cc
> +#define SHMMNI_SYS_FILE "/proc/sys/kernel/shmmni"
Not used.

2021-06-22 11:30 UTC, sighingnow commented on src/server/memory/allocator.cc
> +    LOG(ERROR) << "Failed to read shmmax from 'SHMMAX_SYS_FILE'!";
Here you don't read the fail, please fix the error message.

2021-06-22 11:30 UTC, sighingnow commented on src/server/memory/allocator.cc
> +    LOG(ERROR) << "Failed to read shmmax from 'SHMMAX_SYS_FILE'!";
Use `LOG(WARNING)` please.

2021-06-22 11:30 UTC, sighingnow commented on src/server/memory/allocator.cc
> +    LOG(ERROR) << "'SHMMAX_SYS_FILE' not found!";
Use LOG(WARNING).

2021-06-22 11:30 UTC, sighingnow commented on src/server/memory/allocator.cc
> +    LOG(ERROR) << "Failed to open shmmax from 'SHMMAX_SYS_FILE'!";
Use LOG(WARNING).

2021-06-22 11:30 UTC, sighingnow commented on src/server/memory/allocator.cc
> +    }
There's a syntax error.

2021-06-22 13:52 UTC, Rohan-cod commented
Hi @sighingnow, all the checks and Vineyard CI is passing now.
I assigned a large value to `size` and added a `cout` statement to check if `shmmax` is `less` than `size`:
```
// temp.cc
#include <iostream>
#include <stdio.h>
#ifdef __linux__
#ifndef SHMMAX_SYS_FILE
#define SHMMAX_SYS_FILE "/proc/sys/kernel/shmmax"
#endif
#else
#include <sys/sysctl.h>
#include <sys/types.h>
#endif

int main() {
#ifdef __linux__
  int64_t shmmax = 0;
  FILE* shmmax_file = fopen(SHMMAX_SYS_FILE, "r");
  if (!shmmax_file) {
  	std::cout << "error" << "\n";
  }
  if (fscanf(shmmax_file, "%" PRId64, &shmmax) != 1) {
    fclose(shmmax_file);
    std::cout << "error" << "\n";
  }
  fclose(shmmax_file);
  std::cout << "shmmax -> " << shmmax << "\n";
#else
  int64_t shmmax = 0;
  size_t len = sizeof(shmmax);
  if (-1 == sysctlbyname("kern.sysv.shmmax", &shmmax, &len, NULL, 0)) {
    std::cout << "OSX - error" << "\n";
  }
  std::cout << "shmmax -> " << shmmax << "\n"; 
#endif
  int64_t size = 5000000000;
  if
  	(shmmax < static_cast<float>(size)) {
      std::cout << "'size' is greater than the maximum shared memory size" << "\n";
    }
}
```

Output:

![Screenshot 2021-06-22 at 7 04 01 PM](https://user-images.githubusercontent.com/47586886/122936714-fe49d380-d38e-11eb-9604-33d90956383c.jpg)

2021-06-22 16:15 UTC, sighingnow approved these changes
LGTM. Thank you @Rohan-cod!

2021-06-22 16:15 UTC, merged

2021-06-22 16:36 UTC, Rohan-cod commented
> LGTM. Thank you @Rohan-cod!

Thanks for the guidance @sighingnow. 😇