Memory allocator tests and benchmarks.
v6d-io/v6d pull request #438
Opened 2021-08-14 09:50 UTC by peilii

What do these changes do?
-------------------------

Memory allocator tests and benchmarks.

Related issue number
--------------------

Fixes #issue number

2021-08-14 13:23 UTC, sighingnow commented
Hi @peilii,

Thanks for the effort. Could you please rename the directory to `benchmark`? `bench-x` looks a bit strange.

2021-08-14 15:14 UTC, peilii commented
> Hi @peilii,
> 
> Thanks for the effort. Could you please rename the directory to `benchmark`? `bench-x` looks a bit strange.

No problem at all!

2021-08-15 07:03 UTC, sighingnow requested changes

2021-08-15 13:04 UTC, peilii commented on src/common/memory/jemalloc.cc
> +
No problem. I will look into what's going on.

2021-08-16 00:27 UTC, peilii commented on src/common/memory/jemalloc.cc
> +
Hi @sighingnow,
I would revert the change made in jemalloc.cc for this pull request, and find out what's going on in the next couple of days.

2021-08-16 01:50 UTC, sighingnow commented
Please fix the format & lint error.

2021-08-16 03:29 UTC, peilii commented
> Please fix the format & lint error.

I suppose it's done now. Should I also fix the Codacy Static Code Analysis problem?

2021-08-16 03:58 UTC, sighingnow commented
>  Should I also fix the Codacy Static Code Analysis problem?

It doesn't matter.

2021-08-16 03:59 UTC, sighingnow approved these changes
LGTM.

2021-08-16 03:59 UTC, merged

2021-08-16 03:59 UTC, sighingnow commented
Merged. Thanks!

2021-08-16 04:02 UTC, peilii commented
> Merged. Thanks!

No problem! Thanks!